export const categories = ['Áo', 'Quần', 'Giày dép', 'Phụ kiện'];
//export const suggestCategories = ['Áo khoác', 'Đồ ngủ', 'Túi', 'Nón', 'Đồ thú cưng'];

export const subCategoris = [
  'Áo không tay',
  'Áo tay ngắn',
  'Áo tay dài',
  'Áo Sweater',
  'Áo Hoodie / Zip-up Hoodie ',
  'Sơmi/Blouses',
  'Áo Polo',
  'Áo Croptop',
  'Áo thun Basic',
  'Áo Anorak / Coach jacket',
  'Áo khoác bomber',
  'Áo khoác thể thao',
  'Áo khoác Denim',
  'Áo khoác da/biker',
  'Áo gió',
  'Áo khoác Jumper',
  'Áo Blazer',
  'Quần Denim',
  'Quần ngắn',
  'Quần dài',
  'Quần tây/Slacks',
  'Quần Jogger',
  'Skirt',
  'Leggings',
  'Yếm/Dungarees',
  'Quần lót',
  'Túi đeo chéo',
  'Bóp/Ví',
  'Ví cầm tay',
  'Ba lô',
  'Túi Tote',
  'Túi trống du lịch',
  'Túi bao tử',
  'Travel tag',
  'Giày vải bố',
  'Giày thể thao',
  'Giày chạy bộ',
  'Giày bóng rổ',
  'Giày Sandal/Dép',
  'Nón lưỡi trai',
  'Snapback',
  'Nón len',
  'Nón tai bèo',
  'Khẩu trang',
  'Khăn quàng cổ',
  'Vớ',
  'Thắt lưng',
  'Vòng tay',
  'Nhẫn',
  'Dây chuyền',
  'Bông tai',
  'Găng tay',
  'Móc chìa khóa',
  'Mắt kính',
  'Ốp lưng Iphone',
  'Huy hiệu ',
  'Dây đeo kính',
  'Pet items',
];
